cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import profile

app_name = 'common'

urlpatterns = [
    path('', views.index, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/', views.detail, name='detail'), #마이페이지
    path('profile/', profile, name='user-profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from common import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
    path('', views.index, name='index'),
    path(r'^calendar/$', include('cal.urls')),
    #path('map/', include('map.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'
urlpatterns = [

    path('', views.board, name='board'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('course/', views.course),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from django.contrib.auth import get_user_model

# user 확장
# (id, 비밀번호, 이메일, 이름, 전화번호, 주소)

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=13)
    address = models.CharField(max_length=100)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

# 위치 중요!!! 무조건 class보다 아래에 있어야 함!
User = get_user_model()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

from django.contrib.auth import get_user_model
User = get_user_model()


# 추가

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    name = forms.CharField(label="이름")
    phone = forms.CharField(label="전화번호")
    address = forms.CharField(label="주소")

    class Meta(UserCreationForm):

        model = User
        fields = ("username", "password1", "password2", "email", "name", "phone", "address")

#mypage userform
class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from common.forms import UserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth import get_user_model
from .forms import UpdateUserForm, UpdateProfileForm

User = get_user_model()

# Create your views here.
def index(request):
    return render(request, 'common/main.html')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

#마이페이지
def detail(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user
    }
    return render(request, 'common/detail.html', context)


# new 마이페이지
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'common/profile.html', {'user_form': user_form, 'profile_form': profile_form})

templates/common/detail.html
{% extends 'base.html' %}
{% block body %}
<h1 style="color:blue">{{ user.pk }} : {{ user.username }}</h1>
<hr>
{% endblock %}

templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}

<div class="mainlogo">
    <img class="mainimg" src="../../static/masilgaja.png" alt="masil-img">
</div>
<div class="container my-3" id="b">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:''}}">
        </div>
        <div class="btns">
            <button type="submit" class="btn btn-primary" style="background-color:#b5d692; border:none;">로그인</button>
            <br><br>
            <button type="submit" class="btn btn-secondary" style="background-color:#c0c0c0; border:none;">id 찾기</button>
            <button type="submit" class="btn btn-secondary" style="background-color:#c0c0c0; border:none;">비밀번호 찾기</button>
        </div>
        </form>
</div>
{% endblock %}
</body>
</html>

templates/common/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet"
	href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script
	src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
	$(document).ready(function() {
		$('.slider').bxSlider({
			auto : true,
			speed : 1000,
			pause : 2500,
			mode : 'fade',
			pager : false,
			autoHover : true,
		});
	});
</script>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<p style="text-align:right">
    {% if user.is_authenticated %}
        <a href="{% url 'common:logout' %}">로그아웃</a>
    {% else %}
        <a href="{% url 'common:login' %}">로그인</a>
    {% endif %}
    {% if not user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:signup' %}" style="display:inline">회원가입</a>
    {% endif %}
    <img src="../static/사람사진.png" alt="..." id="img2">
</p>
<div class="a">
    <div class="text-center" id="masil">
        <img src="../static/마실가자.png" alt="...">
    </div>
        <form action="#" method="" id="search">
            <div class="input-group mt-3">
                <input  name="" type="text" class="form-control" placeholder="검색어 입력">
                <button class="btn btn-success" type="submit">검색</button>
            </div>
        </form>
        <div class="slider">
            <div><img src="static/image/서울둘레길1코스1.jpg" /></div>
            <div><img src="static/image/서울둘레길1코스2.jpg" /></div>
            <div><img src="static/image/서울둘레길2코스1.jpg" /></div>
            <div><img src="static/image/서울둘레길2코스2.jpg" /></div>
            <div><img src="static/image/서울둘레길3코스1.jpg" /></div>
            <div><img src="static/image/서울둘레길3코스2.jpg" /></div>
            <div><img src="static/image/서울둘레길4코스1.jpg" /></div>
            <div><img src="static/image/서울둘레길4코스2.jpg" /></div>
            <div><img src="static/image/서울둘레길6코스1.jpg" /></div>
            <div><img src="static/image/서울둘레길6코스2.jpg" /></div>
            <div><img src="static/image/서울둘레길6코스3.jpg" /></div>
	    </div>

        <div style="margin: 30px 0px 0px 0px;">
            <div class="btn btn-success btn-lg" style="width:140px; height:80px;" >테마</div>
            <a href="{% url 'cal:calendar' %}"><div class="btn btn-success btn-lg" style="width:140px; height:80px;">동행</div></a>
            <a href="{% url 'pybo:board' %}"><div class="btn btn-success btn-lg" style="width:140px; height:80px;">게시판</div></a>
            <div class="btn btn-success btn-lg" style="width:140px; height:80px;">채팅</div>
        </div>
</div>
{% endblock %}
</body>
</html>

templates/common/profile.html
{% extends "base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <div class="row my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                            {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                            {{ user_form.email }}
                    </div>
                    <div class="form-group">
                        <a href="#">Change Password</a>
                        <hr>
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
            <button type="reset" class="btn btn-dark btn-lg">Reset</button>
        </form>
    </div>
{% endblock content %}

templates/common/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <!-- 유저 확장 후 회원 가입 항목 추가(이름, 주소, 전화번호) -->

       <div class="mb-3">
            <label for="address">주소</label>
            <input type="text" class="form-control" name="address" id="address"
                   value="{{ form.name.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="name">이름</label>
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="phone">전화번호</label>
            <input type="text" class="form-control" name="phone" id="phone"
                   value="{{ form.phone.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}
</body>
</html>